name: pneumo_reproducibility_env
r_version: R version 4.4.2 (2024-10-31)
platform: x86_64-pc-linux-gnu
packages:
  yaml: 2.3.12
  rlang: 1.1.4
  magrittr: 2.0.3
  cowplot: 1.1.3
  dlnm: 2.4.7
  raster: 3.6-26
  forcats: 1.0.0
  stringr: 1.5.1
  readr: 2.1.5
  tibble: 3.2.1
  tidyverse: 2.0.0
  gridExtra: '2.3'
  purrr: 1.0.2
  RColorBrewer: 1.1-3
  GHRmodel: 0.2.0
  lubridate: 1.9.3
  scales: 1.3.0
  viridis: 0.6.5
  viridisLite: 0.4.2
  INLA: 24.05.10
  sp: 2.1-4
  Matrix: 1.7-2
  sf: 1.0-17
  patchwork: 1.3.0
  ggplot2: 3.5.2
  tidyr: 1.3.1
  dplyr: 1.1.4
  data.table: 1.16.0
  gtable: 0.3.5
  xfun: '0.57'
  lattice: 0.22-5
  tzdb: 0.4.0
  vctrs: 0.6.5
  tools: 4.4.2
  generics: 0.1.3
  proxy: 0.4-27
  fansi: 1.0.6
  pkgconfig: 2.0.3
  KernSmooth: 2.23-26
  lifecycle: 1.0.4
  compiler: 4.4.2
  farver: 2.1.2
  fmesher: 0.1.7
  munsell: 0.5.1
  terra: 1.7-78
  codetools: 0.2-19
  htmltools: 0.5.9
  class: 7.3-23
  pillar: 1.9.0
  classInt: 0.4-10
  nlme: 3.1-167
  tidyselect: 1.2.1
  digest: 0.6.37
  stringi: 1.8.4
  splines: 4.4.2
  fastmap: 1.2.0
  grid: 4.4.2
  colorspace: 2.1-1
  cli: 3.6.3
  utf8: 1.2.4
  e1071: 1.7-16
  withr: 3.0.1
  timechange: 0.3.0
  rmarkdown: '2.31'
  hms: 1.1.3
  tsModel: 0.6-2
  evaluate: 1.0.0
  knitr: '1.51'
  mgcv: 1.9-3
  Rcpp: 1.1.1
  glue: 1.7.0
  DBI: 1.2.3
  rstudioapi: 0.16.0
  R6: 2.5.1
  units: 0.8-5
